//! # D-Bus interface proxy for: `org.freedesktop.impl.portal.FileChooser`
//!
//! This code was generated by `zbus-xmlgen` `5.4.1` from D-Bus introspection data.
//! Source: `file_chooser.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//!
//! [Writing a client proxy]: https://z-galaxy.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
pub struct FileChooser {

}

use std::process::Command;

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use zbus::{interface, zvariant::{DeserializeDict, LE, SerializeDict, Type, serialized::Context}};

#[derive(DeserializeDict, SerializeDict, Type)]
#[zvariant(signature = "dict")]
struct FileChooserResult {
    uris: Vec<String>
}

#[interface(
    name = "org.freedesktop.impl.portal.FileChooser"
)]
impl FileChooser {
    /// OpenFile method
    #[allow(clippy::too_many_arguments)]
    fn open_file(
        &self,
        handle: zbus::zvariant::ObjectPath<'_>,
        app_id: &str,
        parent_window: &str,
        title: &str,
        options: std::collections::HashMap<&str, zbus::zvariant::Value<'_>>,
    ) -> (u32, FileChooserResult) {
        let id = Uuid::new_v4().to_string();
        let mut file_path = std::env::temp_dir();
        file_path.push("xdg-desktop-portal-nvim");
        file_path.push(id);
        std::fs::create_dir_all(&file_path.parent().unwrap_or(&file_path)).expect("failed to create file picker tmp dir");
        Command::new("kitty")
            .arg("nvim")
            .arg(std::env::home_dir().map_or("/".to_owned(), |path| path.to_str().unwrap_or("/").to_owned()).as_str())
            .arg("+au BufReadPost * lua local path = vim.fn.expand('%:p'); vim.cmd('ene!'); vim.api.nvim_paste(path,false,-1); vim.cmd('w ".to_owned() + file_path.to_str().expect("failed to stringify file path") + "'); vim.cmd('qa!')") // When a file is
                                                                                  // opened, copy
                                                                                  // its name
            .output()
            .expect("failed to exec kitty");
        match std::fs::read_to_string(&file_path) {
            Ok(uri) => {
                //let mut map = std::collections::HashMap::new::<String, zbus::zvariant::OwnedValue>();
                //let ctxt = Context::new_dbus(LE, 0);
                let uris = vec!["file://".to_owned() + uri.as_str()];
                //map.insert("uris".to_owned(), to_bytes(ctxt, &uris).expect("failed to encode uris").to_owned());
                //map.insert("uris".to_owned(), OwnedValue::from(uris));
                let _ = std::fs::remove_file(file_path);

                tracing::info!("URIs: {}", uris.join(" "));
                
                (0, FileChooserResult {uris: uris})
            },
            Err(_) => {
                (1, FileChooserResult {uris: vec![]})
            }
        }
        // std::collections::HashMap::new()
    }

    /// SaveFile method
    #[allow(clippy::too_many_arguments)]
    fn save_file(
        &self,
        handle: zbus::zvariant::ObjectPath<'_>,
        app_id: &str,
        parent_window: &str,
        title: &str,
        options: std::collections::HashMap<&str, zbus::zvariant::Value<'_>>,
    ) -> std::collections::HashMap<String, zbus::zvariant::OwnedValue> {
        std::collections::HashMap::new()
    }

    /// SaveFiles method
    #[allow(clippy::too_many_arguments)]
    fn save_files(
        &self,
        handle: zbus::zvariant::ObjectPath<'_>,
        app_id: &str,
        parent_window: &str,
        title: &str,
        options: std::collections::HashMap<&str, zbus::zvariant::Value<'_>>,
    ) -> std::collections::HashMap<String, zbus::zvariant::OwnedValue> {
        std::collections::HashMap::new()
    }
}
